### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by huyhomie66** [saga-slice/saga-slice#14]
import { createStore, applyMiddleware } from "redux";
import createSagaMiddleware from "redux-saga";
import { rootSaga, rootReducer } from "saga-slice";

import slice from "./slice";

const modules = [slice];
const bindMiddleware = (middleware) => {
  if (process.env.NODE_ENV !== "production") {
    const { composeWithDevTools } = require("redux-devtools-extension");
    return composeWithDevTools(applyMiddleware(...middleware));
  }
  return applyMiddleware(...middleware);
};

const sagaMiddleware = createSagaMiddleware();

const appReducer = rootReducer(modules, {
  myExtraReducer: (state, action) => {},
});

const middleware = applyMiddleware(...[sagaMiddleware]);

const store = createStore(appReducer, bindMiddleware([sagaMiddleware]));

sagaMiddleware.run(rootSaga(modules));

store.sagaTask = sagaMiddleware.run(rootSaga(modules));

export default store;

export const wrapper = createWrapper(store, { debug: true });

I make store with next js take regeneratorRuntime error

**Comment by damusix** [comment]
https://github.com/saga-slice/saga-slice/issues/16
