### ISSUE TITLE
Fixed regenerator-runtime

### ISSUE THREAD

**Issue by huyhomie66** [saga-slice/saga-slice#16]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `saga-slice@1.2.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/saga-slice/dist/index.js b/node_modules/saga-slice/dist/index.js
index 2c5d15a..5e6b925 100644
--- a/node_modules/saga-slice/dist/index.js
+++ b/node_modules/saga-slice/dist/index.js
@@ -1,5 +1,7 @@
 'use strict';
 
+require( "regenerator-runtime/runtime")
+
 Object.defineProperty(exports, '__esModule', { value: true });
 
 function _interopDefault (ex) { return (ex && (typeof ex === 'object') && 'default' in ex) ? ex['default'] : ex; }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by damusix** [comment]
@huyhomie66 you should actually run that as the first require in your project's entry point

`src/index.js`
```
import 'regenerator-runtime/runtime';

// or cjs
require('regenerator-runtime/runtime');

// ... rest of your project
```

Any other libraries that use generators may also error if you do not include this depending on your babel config.
